export {};
const express = require('express');
const router = express.Router();
const controllerListAllPost = require('../controller/post/listAllPost');
const controllerFindOnePost = require('../controller/user/findUserById');
const controllerCreatePost = require('../controller/post/createPost');
const controlerDeletePost = require('../controller/post/deletePostWithId');
const controllerDeleteAllPost = require('../controller/post/deleteAllPost');
router.get('/', controllerListAllPost);
router.post('/create', controllerCreatePost);
router.get('/deleteAll', controllerDeleteAllPost);
router.get('/delete/:postId', controlerDeletePost);
router.get('/:postId', controllerFindOnePost);
module.exports = router;
