export {};
const express = require('express');
const router = express.Router();
const controllerListAllUser = require('../controller/user/listAllUser');
const controllerFindOneUser = require('../controller/user/findUserById');
const controllerCreateUSer = require('../controller/user/createUser');
const controllerDeleteUser = require('../controller/user/deleteUserWithId');
const controllerLogin = require('../controller/user/checkLogin');
const controllerLogout = require('../controller/user/logout');
const middleWareStopIfAuth = require('../middlewares/stopIfNotAuth');
const middleWareStopIfNotAuth = require('../middlewares/stopIfNotAuth');
const controlerDeleteAllUser = require('../controller/user/deleteAllUser');
router.get('/', middleWareStopIfNotAuth, controllerListAllUser);

router.get('/removeall', controlerDeleteAllUser);
router.post('/signup', controllerCreateUSer);
router.post('/delete/:userId', controllerDeleteUser);
router.post('/login', controllerLogin);
router.get('/:userId', controllerFindOneUser);
// router.get('/logout', controllerLogout);
module.exports = router;
